version: '3'

services:
  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web
      - api
  db:
    image: postgres:10-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'postgres'
  api:
    build: ./api
    restart: always
    entrypoint: ['pipenv', 'run', 'python', './simple/manage.py', 'runserver', '0.0.0.0:8000']
    volumes:
      - ./api:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  web:
    build: ./web
    restart: always
    entrypoint: ['npm', 'start']
    volumes:
      - ./web:/code
    ports:
      - "3000:3000"

volumes:
  postgres_data: